packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - core-js-pure
  - esbuild
  - msw
  - prisma
  - sharp
