import type { Metadata } from "next";
import { ConvexProvider } from "@/app/_components/convex-provider";
import "@/app/globals.css";
import { ThemeProvider } from "./_components/theme-provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<script
					crossOrigin="anonymous"
					src="//unpkg.com/react-scan/dist/auto.global.js"
				/>
			</head>
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<ConvexProvider>{children}</ConvexProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
